blank_issues_enabled: true
contact_links:
  - name: Feature request 功能请求
    about: Please use Discussions for feature requests. 请在讨论区提出功能请求。
    url: https://github.com/secretflow/platform-web/discussions/new?category=enhancements
